version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: "daily"
    labels: 
      - "automerge"
  - package-ecosystem: "mix"
    directory: "/"
    schedule: 
      interval: "daily"
    labels: 
      - "automerge"
