name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
      - name: Create Cache Dir
        run: mkdir -p priv/plts
      - name: Cache Dialyzer PLT
        uses: actions/cache@v2.1.5
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Check Typespecs
        run: mix dialyzer --halt-exit-status --format term
